### ISSUE TITLE
freescout-app is not able to connect to freescout-db

### ISSUE THREAD

**Issue by erohtar** [tiredofit/docker-freescout#109]
### Summary

Trying to run in Docker+Portainer. `freescout-app` is not able to connect to `freescout-db`

### Steps to reproduce

I mostly followed video instructions at: https://www.youtube.com/watch?v=vw9boxStxyc&t=191s
And used noProxy compose from examples folder.

### Relevant logs and/or screenshots

freescout-app log keeps repeating `[WARN] ** [freescout] MySQL/MariaDB Server 'freescout-db' is not accessible, retrying..` every 5 seconds.

And `freescout-db` log, **which I don't think ever completes loading**, is stuck at:
```
2023-02-02.[18:08:43](https://www.youtube.com/watch?v=vw9boxStxyc&t=43200s) [NOTICE] ** [monitoring] Container configured for monitoring with 'zabbix classic'
2023-02-02.[18:08:43](https://www.youtube.com/watch?v=vw9boxStxyc&t=43200s) [NOTICE] ** [scheduling] Disabling Scheduling
sed: /etc/logrotate.d/mariadb: No such file or directory
2023-02-02.[18:08:44](https://www.youtube.com/watch?v=vw9boxStxyc&t=43200s) [WARN] ** [mariadb] MariaDB directory already present, skipping database creation
2023-02-02.[18:08:44](https://www.youtube.com/watch?v=vw9boxStxyc&t=43200s) [NOTICE] ** [mariadb-backup] Disabling scheduled backups
2023-02-02.[18:08:44](https://www.youtube.com/watch?v=vw9boxStxyc&t=43200s) [STARTING] ** [mariadb] [1] Starting MariaDB 10.6.7
2023-02-02.[18:08:44](https://www.youtube.com/watch?v=vw9boxStxyc&t=43200s) [STARTING] ** [monitoring] [1] Starting Zabbix Agent (classic) 6.0.0
```

### Environment

Here's my compose
```
version: '2'

services:
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    ports:
    - 8001:80
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - /home/admin/Docker/freescout/data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    - /home/admin/Docker/freescout/modules:/www/html/Modules
    - /home/admin/Docker/freescout/logs/:/www/logs
    environment:
    - CONTAINER_NAME=freescout-app
    
    - DB_HOST=freescout-db
    - DB_NAME=freescout
    - DB_USER=admin
    - DB_PASS=XXXX

    - SITE_URL=http://my-tailscale-node:8001
    - ADMIN_EMAIL=XXXX
    - ADMIN_PASS=XXXX
    - ENABLE_SSL_PROXY=FALSE
    - DISPLAY_ERRORS=FALSE
    - ENABLE_AUTO_UPDATE=FALSE
    - TIMEZONE=America/Los_Angeles
    - SHOW_OUTPUT=TRUE
    restart: always

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - /home/admin/Docker/freescout/db:/var/lib/mysql
    environment:
      - ROOT_PASS=XXXX
      - DB_NAME=freescout
      - DB_USER=admin
      - DB_PASS=XXXX
      - CONTAINER_NAME=freescout-db
    restart: always

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
     - freescout-db
    volumes:
      - /home/admin/Docker/freescout/dbbackup:/backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=admin
      - DB_PASS=XXXX
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    restart: always
```
