### ISSUE TITLE
Deletion of Activity Logging is not working

### ISSUE THREAD

**Issue by lucollab** [tiredofit/docker-freescout#128]
### Summary
Hey,

I want to reduce my logging activities concerning user behavior (activity logs) to a minimum. 

The only way I could find to do this on FreeScout is the following:

Set the Variable "ACTIVITY_LOGGER_DELETE_RECORDS_OLDER_THAN_DAYS" to "1"

https://github.com/freescout-helpdesk/freescout/wiki/Configuration-Options

But also after several days the logs are still there and shown in the admin section.

### Steps to reproduce

1. Setup FreeScout with this docker-image
2. Complete steps of configuration
3. Do some login/logout actions for some days
4. Check the logs

### What is the expected *correct* behavior?

Logs will be deleted after 1 Day.

### Environment

- Image version / tag:  1.16.39
- Host OS: Ubuntu

<details>
<summary>Any logs | docker-compose.yml

Freescout ist not showing any errors in the log-files.

**My .env-File looks like that:**

```ACTIVITY_LOGGER_DELETE_RECORDS_OLDER_THAN_DAYS=1```

**My Docker-compse looks like that:**
```
version: '2'
services:
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    ports:
    - 8081:80
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - ./data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    - ./logs/:/www/logs
    env_file:
    - .env
    environment:
    - NO_PROXY=localhost
    - CONTAINER_NAME=freescout-app
    - ACTIVITY_LOGGER_DELETE_RECORDS_OLDER_THAN_DAYS=1
.....
```
</summary>
</details>

    
### Possible fixes

1. Is it possible that this variable may not be included in this image?
2. Is there a way to trigger the empty log action otherwise?
