### ISSUE TITLE
 No Database Host Entered! - Set '$DB_HOST'

### ISSUE THREAD

**Issue by Grievous-Spinout** [tiredofit/docker-freescout#139]
### Summary

found someone else in an old issue #131 who have the exact same problem as me

### Steps to reproduce

build using this yml file
```
version: '2'

services:
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    ports:
    - 8080:80
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    # - ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - ./data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    - ./modules:/www/html/Modules
    - ./logs/:/www/logs
    environment:
    - CONTAINER_NAME=freescout-app
    
    - DB_HOST=freescout-db
    - DB_NAME=${freescout-dbname}
    - DB_USER=${freescout-dbuser}
    - DB_PASS=${freescout-dbpass}

    - SITE_URL=${freescout-url}
    - ADMIN_EMAIL=${freescout-admin}
    - ADMIN_PASS=${freescout-adminpass}
    - ENABLE_SSL_PROXY=FALSE
    - DISPLAY_ERRORS=FALSE
    - TIMEZONE=Europe/Copenhagen
    
    restart: unless-stopped

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=${freescout-rootpass}
      - DB_NAME=${freescout-dbname}
      - DB_USER=${freescout-dbuser}
      - DB_PASS=${freescout-dbpass}

      - CONTAINER_NAME=freescout-db
    restart: unless-stopped

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
     - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=${freescout-dbname}
      - DB_USER=${freescout-dbuser}
      - DB_PASS=${freescout-dbpass}
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    restart: unless-stopped
```

### Relevant logs and/or screenshots

![2023-07-19_11-38](https://github.com/tiredofit/docker-freescout/assets/10957952/22878c84-9fa5-477c-9f05-0559cf203f5e)

### Environment

- used the example docker-compose file
- Host OS: ubuntu ( coolify )

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>
