### ISSUE TITLE
Experiencing 504 timeout with no way to access to freescout

### ISSUE THREAD

**Issue by altdsoy** [tiredofit/docker-freescout#174]
### Summary

We have a docker instance of Freescout that was running just fine and now all of a sudden we are getting 504 Timeout errors.
Restarting the `docker compose` stack do not solve the issue.

The logs in the container side does not show anything useful:
<details>
<summary>Container log:</summary>

```
2024-04-26.20:06:22 [NOTICE] ** [container-init] Detected Container that has been restarted - Cleaning '/tmp/.container' files
2024-04-26.20:06:23 [NOTICE] ** [monitoring] Container configured for monitoring with 'zabbix modern'
2024-04-26.20:06:23 [NOTICE] ** [scheduling] Container configured for scheduled tasks with 'cron'
2024-04-26.20:06:23 [NOTICE] ** [messaging] Container configured to route mail via SMTP to 'postfix-relay'
2024-04-26.20:06:26 [INFO] ** [freescout] Auto Configuring based on Environment Variables
2024-04-26.20:06:28 [WARN] ** [freescout] Installing Modules into container
2024-04-26.20:06:28 [WARN] ** [freescout] Running any Database Migrations
2024-04-26.20:06:30 [INFO] ** [freescout] Initialization Complete. Please visit https://my.freescout.com and login with your credentials..
2024-04-26.20:06:30 [STARTING] ** [nginx] [1] Starting nginx 1.25.4
2024-04-26.20:06:30 [STARTING] ** [php-fpm] [1] Starting php-fpm 8.2.17
2024-04-26.20:06:30 [STARTING] ** [monitoring] [1] Starting Zabbix Agent (modern) 6.4.13
2024-04-26.20:06:31 [STARTING] ** [scheduling] [1] Starting cron
```
</details>

And unfortunately it's the same on Freescout side. Her are the only non empty logs I have:
<details>
<summary>logs/freescout/fetch-emails.log:</summary>

```
[2024-04-26 20:07:02] Fetching UNREAD emails for the last 3 days.
[2024-04-26 20:07:02] Mailbox: Customer Service
[2024-04-26 20:07:02] Folder: Customer Service
[2024-04-26 20:07:02] Fetched: 0
[2024-04-26 20:07:02] Mailbox: Support
[2024-04-26 20:07:03] Folder: Support
[2024-04-26 20:07:03] Fetched: 0
[2024-04-26 20:07:03] Mailbox: Comment
[2024-04-26 20:07:03] Folder: Comment
[2024-04-26 20:07:04] Fetched: 0
[2024-04-26 20:07:04] Fetching finished
```
</details>

<details>
<summary>logs/php-fpm/access.log:</summary>

```
[26-Apr-2024 20:06:17] NOTICE: Terminating ...
[26-Apr-2024 20:06:17] NOTICE: exiting, bye-bye!
[26-Apr-2024 20:06:30] NOTICE: fpm is running, pid 1447
[26-Apr-2024 20:06:30] NOTICE: ready to handle connections
```
</details>
### Steps to reproduce

It happened all of a sudden.

Earlier today it was just working fine.

### Environment

I have the server behind Traefik.

And tried restarting Traefik as well.

No errors in Traefik.

- Image version / tag:  Latest (at the time of running on April 4th - not sure of the actual version as it's not running)
- Host OS: Debian

<details>
<summary>Here is my entire `docker-compose.yml`:</summary>

```
version: '2'

services:
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    # - ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - /root/freescout/data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    # - /root/freescout/modules:/www/html/Modules
    - /root/freescout/logs/:/www/logs
    environment:
    - CONTAINER_NAME=freescout-app
    - DB_HOST=freescout-db
    - DB_NAME=freescout
    - DB_USER=freescout
    - DB_PASS=abc
    - SITE_URL=https://my.freescout.com
    - ADMIN_EMAIL=admin@my.freescout.com
    - ADMIN_PASS=xyz
    - ENABLE_SSL_PROXY=FALSE
    - DISPLAY_ERRORS=FALSE
    - TIMEZONE=America/Los_Angeles
    restart: always
    networks:
      - freescout
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freescout.rule=Host(`my.freescout.com`)"
      - "traefik.http.routers.freescout.entrypoints=https"
      - "traefik.http.routers.freescout.tls=true"
      - "traefik.http.routers.freescout.tls.certresolver=traefik_resolver"

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - /root/freescout/db:/var/lib/mysql
    environment:
      - ROOT_PASS=jkl
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=abc
      - CONTAINER_NAME=freescout-db
    restart: always
    networks:
      - freescout

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
     - freescout-db
    volumes:
      - /root/freescout/dbbackup:/backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=abc
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    restart: always
    networks:
      - freescout

networks:
  freescout:
  traefik:
    external: true

```
</details>

    
### Possible fixes
I have no clue.

What can I look inside the container besides the log files that's also mostly empty?

I remember having something equivalent a few weeks back but it was an issue on my docker compose configuration as I did somehow enabled all of the volumes. Now I only have 2.

It's really annoying to not have any clue about what's going on.
Any help is much appreciated as I'm getting tired of IT as well :)
