### ISSUE TITLE
failing to load scripts

### ISSUE THREAD

**Issue by Kukks** [tiredofit/docker-freescout#18]
Hi! thanks for making a docker image for this.

I'm trying to integrate this into our docker stack ( https://github.com/btcpayserver/btcpayserver-docker), where we use nginx and the lets encrypt companion. I've set up nginx to load this at  a subpath of our main domain, and the login page does show up but noneof the scripts and styles load and give the following error in the console:
```
Loading failed for the <script> with source “https://payjoin.kukks.org/freescout/js/builds/20930ab83e62f6d3f1e94be59e56cb7122231847977.js”.
```

You can see the issue at https://payjoin.kukks.org/freescout

In Nginx, we're using the following config:
```tmpl
{{ if (eq $serviceName "freescout") }}
	location /freescout/ {
		proxy_set_header Connection "";
		proxy_set_header        Host               $host;
		proxy_set_header        X-Real-IP          $remote_addr;
		proxy_set_header        X-Forwarded-For    $proxy_add_x_forwarded_for;
		proxy_set_header        X-Forwarded-Host   $host:443;
		proxy_set_header        X-Forwarded-Server $host;
		proxy_set_header        X-Forwarded-Port   443;
		proxy_set_header        X-Forwarded-Proto  https;
		proxy_pass http://freescout;
	}
{{ end }}
```

and this is the freescout docker config
```yml
  freescout:
    image: tiredofit/freescout
    container_name: freescout
    environment:
      - DB_HOST=freescout-db
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - SITE_URL=${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/freescout
      - ADMIN_EMAIL=admin@admin.com
      - ADMIN_PASS=admin@admin.com
      - ENABLE_SSL_PROXY=TRUE
      - DISPLAY_ERRORS=TRUE
    links:
      - freescout-db
    expose:
      - "80"
    volumes:
      - "freescout_rootdir:/www/html"
      - "freescout_logsdir:/www/logs"
```

Branch with freescout integration: https://github.com/btcpayserver/btcpayserver-docker/tree/freescout
