### ISSUE TITLE
DB_HOST on docker swarm

### ISSUE THREAD

**Issue by knolljo** [tiredofit/docker-freescout#200]
### Summary

I'm running a docker swarm and want to host freescout on it. The freescout-app container cannot connect to the freescout-db container.

### Possible fixes

I think this might be due to the case `DB_HOST` is set to a container name. Docker swarm handles container names differently and prefixes them with their stack name, for example the stack `myfreescout` creates `myfreescout_freescout-app` and `myfreescout_freescout-db`. One solution might be to set the DB_HOST to a URL of the database, that is reachable inside the default network, shared between the two containers, but I have no idea how to do that.

### Steps to reproduce

My current compose file looks like this:
```yaml
services:
  freescout-app:
    image: tiredofit/freescout:latest
    networks:
      - default
    environment:
      - DB_HOST=freescout-db
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout

      - SITE_URL=https://freescout.example.com
      - ADMIN_EMAIL=mail@example.com
      - ADMIN_PASS=password
      - ENABLE_SSL_PROXY=FALSE
      - DISPLAY_ERRORS=FALSE
      - TIMEZONE=Europe/Berlin
    volumes:
      - freescout-data:/var/www/html
    depends_on:
      - freescout-db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.freescout.rule=Host(`example.com`)"
        - "traefik.http.routers.freescout.entrypoints=freescout"
        - "traefik.http.routers.freescout.tls=true"
        - "traefik.http.services.freescout.loadbalancer.server.port=80"

  freescout-db:
    image: tiredofit/mariadb
    volumes:
      - freescout_db:/var/lib/mysql
    environment:
      - ROOT_PASS=root-password
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
    networks:
      - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  default:
  proxy:
    external: true

volumes:
  freescout-data:
  freescout_db:

```
