### ISSUE TITLE
App fails to use existing database.  Terminates abnormally.

### ISSUE THREAD

**Issue by mostlydev** [tiredofit/docker-freescout#53]
### Summary

1.15.8 seems to ignore the existing database and proceeds to start from scratch.  Locking compose to 1.15.7 works as expected.

### Steps to reproduce

```
$ docker-compose pull
$ docker-compose up
```
 when image set to `:latest` when latest is `1.15.8`

### What is the expected *correct* behavior?

Normal migration and startup.

### Relevant logs and/or screenshots

```
freescout-app          | [cont-init.d] 30-freescout: executing...
freescout-app          | 2021-07-21-16:06:48 [WARN] ** [freescout] Potential New Installation / Standalone Installation Detected - Copying Freescout Sourcecode
freescout-app          | 2021-07-21-16:06:48 [WARN] ** [freescout] Detected /data directory. Persistently saving settings/sessions/cache/uploads/modules
freescout-app          | 2021-07-21-16:06:49 [INFO] ** [freescout] Skipping Auto configuration and using in place .env
freescout-app          | 2021-07-21-16:06:49 [WARN] ** [freescout] Detected empty Database - Setting up - Please wait..
```

### Environment

```
  freescout-app:
    image: tiredofit/freescout:latest
    container_name: freescout-app
    links:
      - freescout-db
    volumes:
      - ./data:/data
      - ./logs:/www/logs
    environment:
      VIRTUAL_HOST: ******************
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: *******************
      LETSENCRYPT_EMAIL: ******************
      ZABBIX_HOSTNAME: freescout-app

      DB_HOST: freescout-db
      DB_NAME: freescout
      DB_USER: freescout
      DB_PASS: freescout

      SITE_URL: 'https://************'
      ADMIN_EMAIL: ***************
      ADMIN_PASS: ***********
      ENABLE_SSL_PROXY: 'FALSE'
      DISPLAY_ERRORS: 'FALSE'
      TIMEZONE: America/Toronto
      ENABLE_AUTO_UPDATE: 'TRUE'
    networks:
      - 'net'
    restart: unless-stopped

```
- Image version / tag:  1.15.8
- Host OS: Ubuntu 20.04.2 LTS

There is also some issue with one of the initialization scripts.  It complains about an errant `fi` and the app process stops.
