### ISSUE TITLE
Clean freescout installation is out of date

### ISSUE THREAD

**Issue by woutr-nl** [tiredofit/docker-freescout#72]
### Summary

Clean install of freescout is version 1.7.20 and updating seems to be impossible due to PHP 8

### Steps to reproduce

Do a clean install

### What is the expected *correct* behavior?

Latest version of Freescout

### Relevant logs and/or screenshots

My docker-compose.yml

```
version: '2'

services:

  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - ./data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    - ./modules:/www/html/Modules
    - ./logs/:/www/logs
    environment:
    - CONTAINER_NAME=freescout-app
    - DB_HOST=######
    - DB_NAME=######
    - DB_USER=######
    - DB_PASS=######
    - SITE_URL=######
    - ADMIN_EMAIL=######
    - ADMIN_PASS=######
    - ENABLE_SSL_PROXY=TRUE
    - DISPLAY_ERRORS=FALSE
    - TIMEZONE=Europe/Amsterdam
    labels:
      - "traefik.http.routers.freescout.rule=Host(`######`)"
      - "traefik.http.routers.freescout.tls=true"
      - "traefik.http.routers.freescout.tls.certresolver=lets-encrypt"
      - "traefik.http.services.freescout.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    networks:
      - web
      - internal
    restart: always

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=######
      - DB_NAME=######
      - DB_USER=######
      - DB_PASS=######

      - CONTAINER_NAME=freescout-db
    networks:
      - internal
    restart: always
    labels:
      - traefik.enable=false

networks:
 web:
  external: true
 internal:
  external: false
```

### Environment

- Image version / tag:  see the compose
- Host OS: Docker

    
### Possible fixes

Update freescout to the latest version in the image (?)
