### ISSUE TITLE
Modules lost after docker-compose down

### ISSUE THREAD

**Issue by afawaz2** [tiredofit/docker-freescout#75]
### Summary

I uncommented the "./modules:/www/html/Modules" in my docker-compose.yml file. When I add new modules, I see them in the modules folder. However, when running docker-compose down and docker-compose up -d the modules folder is cleared and Freescout fails because it cannot find the module source.

I want to add custom modules, so I want to be able to persist the folder. Please let me know what I am doing wrong.

### Steps to reproduce

```
version: '2'

services:

  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    ports:
    - "80:80"
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### If you want to just keep the original source and add additional modules uncomment this line
    - ./modules:/www/html/Modules
    - ./logs/:/www/logs
    - ./data/:/data
    environment:
    - VIRTUAL_HOST=XXXXXX
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=XXXXX
    - LETSENCRYPT_EMAIL=XXXXX
    - PHP_MEMORY_LIMIT=512M
      #- APP_DEBUG=true
      #- APP_LOG_LEVEL=debug
    - ZABBIX_HOSTNAME=freescout-app

    - DB_HOST=freescout-db
    - DB_NAME=freescout
    - DB_USER=freescout
    - DB_PASS=XXXXXX
    - SITE_URL=XXXXXXXXXXXX
    - ADMIN_EMAIL=admin@admin.com
    - ADMIN_PASS=XXXXXXXXXXXXX
    - ENABLE_SSL_PROXY=TRUE
    - DISPLAY_ERRORS=FALSE
    - TIMEZONE=America/Chicago
    restart: always

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXX
      - MYSQL_DATABASE=freescout
      - MYSQL_USER=freescout
      - MYSQL_PASSWORD=XXXXXXXXXXXX

      - ZABBIX_HOSTNAME=freescout-db

    restart: always
```
