### ISSUE TITLE
Having trouble getting connected to the db -- db loops with Starting MariaDB 10.6.7

### ISSUE THREAD

**Issue by wnm3** [tiredofit/docker-freescout#76]
I'm probably confused with what to set in the docker-compose.yml and in my .env file.
I'm running MariaDB on my Mac laptop OS version 12.3
I'm starting by running: docker compose up

I get lots of:
```
aahelpdesk-app        | 2022-04-05.13:49:52 [WARN] ** [freescout] MySQL/MariaDB Server 'aahelpdesk-db' is not accessible, retrying.. (375 seconds so far)
aahelpdesk-db         | 2022-04-05.20:49:52 [STARTING] ** [mariadb] [379] Starting MariaDB 10.6.7
aahelpdesk-db         | 2022-04-05.20:49:53 [STARTING] ** [mariadb] [380] Starting MariaDB 10.6.7
aahelpdesk-db         | 2022-04-05.20:49:54 [STARTING] ** [mariadb] [381] Starting MariaDB 10.6.7
aahelpdesk-db         | 2022-04-05.20:49:55 [STARTING] ** [mariadb] [382] Starting MariaDB 10.6.7
aahelpdesk-db         | 2022-04-05.20:49:56 [STARTING] ** [mariadb] [383] Starting MariaDB 10.6.7
aahelpdesk-app        | 2022-04-05.13:49:57 [WARN] ** [freescout] MySQL/MariaDB Server 'aahelpdesk-db' is not accessible, retrying.. (380 seconds so far)
aahelpdesk-db         | 2022-04-05.20:49:57 [STARTING] ** [mariadb] [384] Starting MariaDB 10.6.7
aahelpdesk-db         | 2022-04-05.20:49:58 [STARTING] ** [mariadb] [385] Starting MariaDB 10.6.7
aahelpdesk-db         | 2022-04-05.20:49:59 [STARTING] ** [mariadb] [386] Starting MariaDB 10.6.7
aahelpdesk-db         | 2022-04-05.20:50:00 [STARTING] ** [mariadb] [387] Starting MariaDB 10.6.7
aahelpdesk-db         | 2022-04-05.20:50:01 [STARTING] ** [mariadb] [388] Starting MariaDB 10.6.7
aahelpdesk-app        | 2022-04-05.13:50:02 [WARN] ** [freescout] MySQL/MariaDB Server 'aahelpdesk-db' is not accessible, retrying.. (385 seconds so far)
```
My DB_NAME matches what shows in the show databases; command (aahelpdesk)
My DB_USER matches what shows in select user from mysql.user; command (aahelpdesk)
My DB_PASS matches what I use when logging into mysql -u aahelpdesk -p  (what I enter when prompted).
My DB_HOST is the name of the container for the database

I'm not sure what ROOT_PASS is supposed to be (tried password, and tried my OS user's password as though you might be trying the password required for sudo mysql -u root

I don't have an NGINX set up so set my SITE_URL to use http:// protocol and I set ENABLE_SSL_PROXY to FALSE.

How can I get more detail about why the database isn't starting?

I tried exec'ing into each container to try the mysql -u aahelpdesk -p command but they fail with the socket name set up to point to 3306.

Isof -i :3306 shows mariadb running and listening on 3306 on my localhost.

**Comment by tiredofit** [comment]
I think this is a problem with the MariaDB container itself.
You can try setting `CONTAINER_LOG_LEVEL=DEBUG` on the mariadb container and it will give you the output as to what is failing.
Otherwise head inside the container to `/var/lib/mysql` and there should be `mysql_err.log` sitting in there that would give hints. Sometimes my own images don't work well on other systems as they have opinionated defaults set. If thats the case you can revert to using official mariadb.

**Comment by wnm3** [comment]
No error log in /var/lib/mysql:
```
Nathaniels-MacBook-Pro-2:HelpDesk>docker exec -ti c83c668a2e7a /bin/bash
[tiredofit/mariadb:10.6:3.10.6 21:48:17] # cd /var/lib/mysql
[tiredofit/mariadb:10.6:3.10.6 21:48:24] # ls -l
total 6028
drwx------    3 mariadb  mariadb         96 Apr  5 18:37 aahelpdesk
-rw-r-----    1 mariadb  mariadb     589824 Apr  5 21:48 aria_log.00000001
-rw-r-----    1 mariadb  mariadb         52 Apr  5 21:48 aria_log_control
-rw-r-----    1 mariadb  mariadb        946 Apr  5 18:43 ib_buffer_pool
-rw-r-----    1 mariadb  mariadb  100663296 Apr  5 18:43 ib_logfile0
-rw-r-----    1 mariadb  mariadb   12582912 Apr  5 18:43 ibdata1
-rw-r-----    1 mariadb  mariadb          0 Apr  5 18:37 multi-master.info
drwx------   90 mariadb  mariadb       2880 Apr  5 18:37 mysql
-rw-r--r--    1 mariadb  mariadb         14 Apr  5 18:37 mysql_upgrade_info
drwx------    3 mariadb  mariadb         96 Apr  5 18:37 performance_schema
drwx------  106 mariadb  mariadb       3392 Apr  5 18:37 sys
```
and debug doesn't really tell much:
```
aahelpdesk-db         | 2022-04-05.21:49:05 [DEBUG] ** [mariadb] Checking to see if container initialization scripts have completed
aahelpdesk-db         | 2022-04-05.21:49:05 [DEBUG] ** [mariadb] Checking to see if service has initialized
aahelpdesk-db         | 2022-04-05.21:49:05 [STARTING] ** [mariadb] [125] Starting MariaDB 10.6.7
aahelpdesk-db         | 2022-04-05 21:49:05 0 [Note] /usr/bin/mysqld (server 10.6.7-MariaDB) starting as process 5531 ...
aahelpdesk-db         | 2022-04-05 21:49:05 0 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
aahelpdesk-db         | 2022-04-05.21:49:06 [DEBUG] ** [mariadb] Checking to see if container initialization scripts have completed
aahelpdesk-db         | 2022-04-05.21:49:06 [DEBUG] ** [mariadb] Checking to see if service has initialized
aahelpdesk-db         | 2022-04-05.21:49:06 [STARTING] ** [mariadb] [126] Starting MariaDB 10.6.7
aahelpdesk-db         | 2022-04-05 21:49:06 0 [Note] /usr/bin/mysqld (server 10.6.7-MariaDB) starting as process 5569 ...
aahelpdesk-db         | 2022-04-05 21:49:06 0 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
aahelpdesk-db         | 2022-04-05.21:49:07 [DEBUG] ** [mariadb] Checking to see if container initialization scripts have completed
aahelpdesk-db         | 2022-04-05.21:49:07 [DEBUG] ** [mariadb] Checking to see if service has initialized
aahelpdesk-db         | 2022-04-05.21:49:07 [STARTING] ** [mariadb] [127] Starting MariaDB 10.6.7
aahelpdesk-db         | 2022-04-05 21:49:07 0 [Note] /usr/bin/mysqld (server 10.6.7-MariaDB) starting as process 5607 ...
aahelpdesk-db         | 2022-04-05 21:49:07 0 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
aahelpdesk-db         | 2022-04-05.21:49:08 [DEBUG] ** [mariadb] Checking to see if container initialization scripts have completed
aahelpdesk-db         | 2022-04-05.21:49:08 [DEBUG] ** [mariadb] Checking to see if service has initialized
aahelpdesk-db         | 2022-04-05.21:49:08 [STARTING] ** [mariadb] [128] Starting MariaDB 10.6.7
aahelpdesk-db         | 2022-04-05 21:49:08 0 [Note] /usr/bin/mysqld (server 10.6.7-MariaDB) starting as process 5645 ...
aahelpdesk-db         | 2022-04-05 21:49:08 0 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
aahelpdesk-db         | 2022-04-05.21:49:09 [DEBUG] ** [mariadb] Checking to see if container initialization scripts have completed
aahelpdesk-db         | 2022-04-05.21:49:09 [DEBUG] ** [mariadb] Checking to see if service has initialized
aahelpdesk-db         | 2022-04-05.21:49:09 [STARTING] ** [mariadb] [129] Starting MariaDB 10.6.7
aahelpdesk-db         | 2022-04-05 21:49:09 0 [Note] /usr/bin/mysqld (server 10.6.7-MariaDB) starting as process 5683 ...
aahelpdesk-db         | 2022-04-05 21:49:09 0 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
aahelpdesk-app        | 2022-04-05.14:49:09 [WARN] ** [freescout] MySQL/MariaDB Server 'aahelpdesk-db' is not accessible, retrying.. (125 seconds so far)
```

What is the ROOT_PASS supposed to be and am I okay with the ENABLE_SSL_PROXY=FALSE
And I'm running the MariaDB on my laptop on port 3306 so might there a conflict if your container is also trying to run MariaDB on port 3306?

**Comment by wnm3** [comment]
I have changed the names of the containers to aahelpdesk-app and aahelpdesk-db in the docker-compose.yml file...

Here is a cleansed version of the file:
```
version: '2'

services:
  
  aahelpdesk-app:
    image: tiredofit/freescout
    container_name: aahelpdesk-app
    links:
    - aahelpdesk-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    #- ./data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
    - ./logs/:/www/logs
    environment:
    - VIRTUAL_HOST=aahelpdesk.example.com
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=aahelpdesk.example.com
    - LETSENCRYPT_EMAIL=wnm3@us.ibm.com
    - CONTAINER_LOG_LEVEL=DEBUG

    - CONTAINER_NAME=aahelpdesk-app
    
    - DB_HOST=aahelpdesk-db
    - DB_NAME=aahelpdesk
    - DB_USER=aahelpdesk
    - DB_PASS=password-for-aahelpdesk-user

    - SITE_URL=http://aahelpdesk.example.com
    - ADMIN_EMAIL=admin@admin.com
    - ADMIN_PASS=freescout
    - ENABLE_SSL_PROXY=FALSE
    - DISPLAY_ERRORS=FALSE
    - TIMEZONE=America/Vancouver
    networks:
      - proxy-tier
    restart: always

  aahelpdesk-db:
    image: tiredofit/mariadb
    container_name: aahelpdesk-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=my-mac-user-password
      - DB_NAME=aahelpdesk
      - DB_USER=aahelpdesk
      - DB_PASS=password-for-aahelpdesk-user
      - CONTAINER_LOG_LEVEL=DEBUG

      - CONTAINER_NAME=aahelpdesk-db
    networks:
      - proxy-tier
    restart: always

  aahelpdesk-db-backup:
    container_name: aahelpdesk-db-backup
    image: tiredofit/db-backup
    links:
     - aahelpdesk-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=aahelpdesk-db-backup
      - DB_HOST=aahelpdesk-db
      - DB_TYPE=mariadb
      - DB_NAME=aahelpdesk
      - DB_USER=aahelpdesk
      - DB_PASS=password-for-aahelpdesk-user
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    networks:
      - proxy-tier
    restart: always


networks:
  proxy-tier:
    name: nginx-proxy

```
