### ISSUE TITLE
Can't fetch emails over IMAP

### ISSUE THREAD

**Issue by BrianGilbert** [tiredofit/docker-freescout#8]
```
[2019-07-31 14:29:10] Mailbox: Tech Support
[2019-07-31 14:29:10] Error: imap_open(): Couldn't open stream {imap.gmail.com:993/imap/ssl}. Certificate failure for imap.gmail.com: self signed certificate: /OU=No SNI provided; please fix your client./CN=invalid2.invalid; File: /www/html/vendor/webklex/laravel-imap/src/IMAP/Client.php (230)
[2019-07-31 14:29:10] Fetching finished
```

Installation using recommended nginx-proxy and ssl containers, using a modified version of the docker-compose.yml to start everything up.

```
version: '2'

services:

  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    links:
      - freescout-db
    volumes:
      - ./logs/:/www/logs
    environment:
      - VIRTUAL_HOST=freescout.domain.com.au
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=freescout.domain.com.au
      - LETSENCRYPT_EMAIL=sysops@domain.com.au

      - ZABBIX_HOSTNAME=freescout-app

      - DB_HOST=freescout-db
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout

      - SITE_URL=https://freescout.domain.com.au
      - ADMIN_EMAIL=admin@domain.com.au
#      - ADMIN_PASS=freescout
      - ENABLE_SSL_PROXY=TRUE
      - DISPLAY_ERRORS=FALSE
      - TIMEZONE=Australia/Melbourne
    env_file:
      - .env
    networks:
      - proxy-tier
    restart: always

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=freescout
      - MYSQL_USER=freescout
      - MYSQL_PASSWORD=freescout

      - ZABBIX_HOSTNAME=freescout-db
    env_file:
      - .env
    networks:
      - proxy-tier
    restart: always

  freescout-db-backup:
    image: tiredofit/db-backup
    container_name: freescout-db-backup
    links:
     - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - ZABBIX_HOSTNAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    env_file:
      - .env
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy_default
```
