### ISSUE TITLE
Fatal Error with Redis as Cache Driver

### ISSUE THREAD

**Issue by straccio** [tiredofit/docker-freescout#98]
### Summary

If enabled Redis Cache with CACHE_DRIVER in .env file and adding prods/predis library freescout give a Fatal Error.

### Steps to reproduce

Enable Redis Cache adding "CACHE_DRIVE=redis" to the .env file and run "php /www/html/artisan"

### What is the expected *correct* behavior?

Write the help in the stdout

### Relevant logs and/or screenshots

```
[tiredofit/freescout:1.15.71 08:50:28 /www/html] $ php81 artisan 
PHP Fatal error:  During inheritance of SessionHandlerInterface: Uncaught ErrorException: Return type of Illuminate\Session\CacheBasedSessionHandler::read($sessionId): string|bool should either be compatible with SessionHandlerInterface::read(string $id): string|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/html/vendor/laravel/framework/src/Illuminate/Session/CacheBasedSessionHandler.php:56
Stack trace:
#0 /www/html/vendor/laravel/framework/src/Illuminate/Session/CacheBasedSessionHandler.php(8): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Return type of ...', '/www/html/vendo...', 56)
#1 /www/html/vendor/composer/ClassLoader.php(573): include('/www/html/vendo...')
#2 /www/html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/www/html/vendo...')
#3 /www/html/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(151): Composer\Autoload\ClassLoader->loadClass('Illuminate\\Sess...')
#4 /www/html/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(121): Illuminate\Session\SessionManager->createCacheHandler('redis')
#5 /www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(88): Illuminate\Session\SessionManager->createRedisDriver()
#6 /www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(63): Illuminate\Support\Manager->createDriver('redis')
#7 /www/html/vendor/laravel/framework/src/Illuminate/Session/SessionServiceProvider.php(47): Illuminate\Support\Manager->driver()
#8 /www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(749): Illuminate\Session\SessionServiceProvider->Illuminate\Session\{closure}(Object(Illuminate\Foundation\Application), Array)
#9 /www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#10 /www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('session.store', Array)
#11 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make('session.store', Array)
#12 /www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(1198): Illuminate\Foundation\Application->make('session.store')
#13 /www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(123): Illuminate\Container\Container->offsetGet('session.store')
#14 /www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(94): Illuminate\Auth\AuthManager->createSessionDriver('web', Array)
#15 /www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(68): Illuminate\Auth\AuthManager->resolve('web')
#16 /www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(292): Illuminate\Auth\AuthManager->guard()
#17 /www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Auth\AuthManager->__call('id', Array)
#18 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(152): Illuminate\Support\Facades\Facade::__callStatic('id', Array)
#19 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(113): Illuminate\Foundation\Exceptions\Handler->context()
#20 /www/html/app/Exceptions/Handler.php(40): Illuminate\Foundation\Exceptions\Handler->report(Object(Predis\Connection\ConnectionException))
#21 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(352): App\Exceptions\Handler->report(Object(Predis\Connection\ConnectionException))
#22 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Illuminate\Foundation\Console\Kernel->reportException(Object(Predis\Connection\ConnectionException))
#23 /www/html/artisan(62): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main} in /www/html/vendor/laravel/framework/src/Illuminate/Session/CacheBasedSessionHandler.php on line 8
```

### Environment
BROADCAST_DRIVER=redis
CACHE_DRIVER=redis
SESSION_DRIVER=redis
REDIS_HOST=localhost
REDIS_PASSWORD=Asdf1234
REDIS_PORT=6379

- Image version / tag:  tiredofit/freescout:latest
- Host OS: Debian

<details>
<summary>

```yaml
version: '3.5'
networks:
  backend:
  reverse_proxy:
    name: '${DOCKER_REVERSE_PROXY_NET}'
    external: true

volumes:
  volume_app_data_storage_framework:
    name: '${STACK_NAME}_app_data_storage_framework'
  volume_app_data_storage_app_publick_js:
    name: '${STACK_NAME}_app_data_storage_app_publick_js'
  volume_app_data:
    name: '${STACK_NAME}_app_data${NFS_VOLUME_SUFFIX}'
    external: true
  volume_app_html:
    name: '${STACK_NAME}_app_html${NFS_VOLUME_SUFFIX}'
    external: true
  volume_app_logs:
    name: '${STACK_NAME}_app_logs${NFS_VOLUME_SUFFIX}'
    external: true
  volume_db_mysql:
    name: '${STACK_NAME}_db_mysql'
    external: true
  volume_db_backup:
    name: '${STACK_NAME}_db_backup${NFS_VOLUME_SUFFIX}'
    external: true
  volume_redis_data:
    name: '${STACK_NAME}_redis_data'

services:
  freescout-app:
    image: tiredofit/freescout
    depends_on:
      - freescout-db
      - freescout-redis
    volumes:
      - type: volume
        source: volume_app_data
        target: /data
      - type: volume
        source: volume_app_html
        target: /www/html
      - type: volume
        source: volume_app_logs
        target: /www/logs
      - type: volume
        source: volume_app_data_storage_framework
        target: /data/storage/framework
      - type: volume
        source: volume_app_data_storage_app_publick_js
        target: /data/storage/app/public/js
        
    environment:
    - VIRTUAL_HOST=${FQDN}
    - VIRTUAL_NETWORK=${DOCKER_REVERSE_PROXY_NET}
    - VIRTUAL_PORT=${WEB_PORT}
    - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

    - CONTAINER_NAME=freescout-app
    
    - DB_HOST=freescout-db
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}

    - SITE_URL=https://${FQDN}
    - ADMIN_EMAIL=${ADMIN_EMAIL}
    - ADMIN_PASS=${ADMIN_PASS}
    - ENABLE_SSL_PROXY=${ENABLE_SSL_PROXY}
    - DISPLAY_ERRORS=${DISPLAY_ERRORS}
    - TIMEZONE=${TIMEZONE}

    - CACHE_DRIVER=redis
    - SESSION_DRIVER=redis
    
    - REDIS_HOST=freescout-redis
    - REDIS_PASSWORD=${REDIS_PASS}
    - REDIS_PORT=6379
    networks:
      - backend
      - reverse_proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${STACK_NAME}.rule=Host(`${FQDN}`)"
        - "traefik.http.routers.${STACK_NAME}.entrypoints=${TRAEFIK_ENTRYPOINT}"
        - "traefik.http.routers.${STACK_NAME}.tls.options=default"
        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.port=${WEB_PORT}"

  freescout-db:
    image: tiredofit/mariadb
    volumes:
      - type: volume
        source: volume_db_mysql
        target: /var/lib/mysql
      
    environment:
      - ROOT_PASS=${ROOT_PASS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

      - CONTAINER_NAME=freescout-db
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  freescout-db-backup:
    image: tiredofit/db-backup
    depends_on:
     - freescout-db
    volumes:
      - type: volume
        source: volume_db_backup
        target: /backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DUMP_FREQ=${DB_DUMP_FREQ}
      - DB_DUMP_BEGIN=${DB_DUMP_BEGIN}
      - DB_CLEANUP_TIME=${DB_CLEANUP_TIME}
      - COMPRESSION=BZ
      - MD5=TRUE
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  freescout-redis:
    image: redis/redis-stack:latest
    volumes:
      - type: volume
        source: volume_redis_data
        target: /data
    environment:
      - REDIS_ARGS:'--requirepass ${REDIS_PASS}'
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: any
```
</summary>
</details>
    
### Possible fixes
use php 7.4 instead of 8.1
